### PR TITLE
chore: update discord invite link

### PR DESCRIPTION
**Pull request by erickzhao**
:)

### CODE REVIEW

**Review by ckerr — APPROVED** [review]
:+1: on the idea.

Asking since I just don't know this about Discord -- is that APGC3k5yaH link good for the long term? 

Also, should this be updated elsewhere e.g. https://www.electronjs.org/community#boilerplates and https://github.com/electron/governance/blob/main/playbooks/responses/not-an-issue.md ?

**Review by malept — APPROVED** [review]
Looks legit

**Comment by dsanders11** [comment]
Merging as the test failure is obviously unrelated.

**Comment by erickzhao** [comment]
> Asking since I just don't know this about Discord -- is that APGC3k5yaH link good for the long term?

We actually had the vanity `/electronjs` invite before but we made this one without an expiry date specifically to help track which invites come from GitHub and website links.

**Pull request merged**
